apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: MalinInc Home

    background:
      image: https://cdnb.artstation.com/p/assets/images/images/006/897/659/large/mikael-gustafsson-wallpaper-mikael-gustafsson.jpg
      blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
      saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 100 # 0-100

    theme: dark
    color: slate

    useEqualHeights: true

    layout:
      Hypervisor:
        header: true
        style: row
        columns: 4
      Containers:
        header: true
        style: row
        columns: 4
      DNS:
        header: true
        style: row
        columns: 4
      Network:
        header: true
        style: row
        columns: 4
      Remote Access:
        header: true
        style: row
        columns: 4
      Storage:
        header: true
        style: row
        columns: 4
      Media:
        header: true
        style: row
        columns: 4
      Home Automation:
        header: true
        style: row
        columns: 4
      Other:
        header: true
        style: row
        columns: 4
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - Hypervisor:
        - Proxmox:
            icon: proxmox.svg
            href: {{"{{"}}HOMEPAGE_VAR_PROXMOX_URL{{"}}"}}
            description: PM-01
            widget:
                type: proxmox
                url: {{"{{"}}HOMEPAGE_VAR_PROXMOX_URL{{"}}"}}
                username: {{"{{"}}HOMEPAGE_VAR_PROXMOX_USER{{"}}"}}
                password: {{"{{"}}HOMEPAGE_VAR_PROXMOX_API_KEY{{"}}"}}
                node: PM-01
        - Proxmox:
            icon: proxmox.svg
            href: {{"{{"}}HOMEPAGE_VAR_PROXMOX_URL{{"}}"}}
            description: PM-02
            widget:
                type: proxmox
                url: {{"{{"}}HOMEPAGE_VAR_PROXMOX_URL{{"}}"}}
                username: {{"{{"}}HOMEPAGE_VAR_PROXMOX_USER{{"}}"}}
                password: {{"{{"}}HOMEPAGE_VAR_PROXMOX_API_KEY{{"}}"}}
                node: PM-02
        - Proxmox:
            icon: proxmox.svg
            href: {{"{{"}}HOMEPAGE_VAR_PROXMOX_URL{{"}}"}}
            description: pm-003
            widget:
                type: proxmox
                url: {{"{{"}}HOMEPAGE_VAR_PROXMOX_URL{{"}}"}}
                username: {{"{{"}}HOMEPAGE_VAR_PROXMOX_USER{{"}}"}}
                password: {{"{{"}}HOMEPAGE_VAR_PROXMOX_API_KEY{{"}}"}}
                node: pm-003
    - Containers:
        - ArgoCD:
            icon: argo-cd.svg
            href: {{"{{"}}HOMEPAGE_VAR_ArgoCD_URL{{"}}"}}
            description: k3s
    - DNS:
        - AdGaurd1:
            icon: adguard-home.svg
            href: {{"{{"}}HOMEPAGE_VAR_ADGUARD_URL_1{{"}}"}}
            description: adguard
            widget:
                type: adguard
                url: {{"{{"}}HOMEPAGE_VAR_ADGUARD_URL_1{{"}}"}}
                username: {{"{{"}}HOMEPAGE_VAR_ADGUARD_USER1{{"}}"}}
                password: {{"{{"}}HOMEPAGE_VAR_ADGUARD_API_KEY_1{{"}}"}}
        - AdGuard2:
            icon: adguard-home.svg
            href: {{"{{"}}HOMEPAGE_VAR_ADGUARD_URL_2{{"}}"}}
            description: adguard
            widget:
                type: adguard
                url: {{"{{"}}HOMEPAGE_VAR_ADGUARD_URL_2{{"}}"}}
                username: {{"{{"}}HOMEPAGE_VAR_ADGUARD_USER2{{"}}"}}
                password: {{"{{"}}HOMEPAGE_VAR_ADGUARD_API_KEY_2{{"}}"}}
    - Network:
        - UniFi:
            icon: unifi.svg
            href: {{"{{"}}HOMEPAGE_VAR_UNIFI_NETWORK_URL{{"}}"}}
            description: network
    - Storage:
        - UNAS:
            icon: unifi.svg
            href: {{"{{"}}HOMEPAGE_VAR_UNAS_URL{{"}}"}}
            description: Unas-pro
    - Media:
        - Jellyfin:
            icon: jellyfin.svg
            href: {{"{{"}}HOMEPAGE_VAR_JELLYFIN_URL{{"}}"}}
            description: media server
    - Other:
        - GitHub:
            icon: github.svg
            href: https://github.com
            description: source code
        - IT-tools:
            icon: it-tools.svg
            href: https://ittools.malininc.com
            description: A collection of IT tools
  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
        disk: /

    - datetime:
        text_size: xl
        format:
          timeStyle: short
  docker.yaml: ""