apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-ai
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: vllm-ai
  template:
    metadata:
      labels:
        app: vllm-ai
    spec:
      hostIPC: true
      # Only schedule onto nodes labeled `gpu=true`
      nodeSelector:
        gpu: "true"
      tolerations:
        - key: "gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"  

      containers:
        - name: vllm-ai
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - "--model"
            - "{{ .Values.model }}"
          ports:
            - containerPort: 8000
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vllm-hf-token
                  key: HUGGING_FACE_HUB_TOKEN
            - name: VLLM_LOGGING_LEVEL
              value: DEBUG        
          volumeMounts:
            - name: huggingface-cache
              mountPath: /root/.cache/huggingface
            - name: dshm
              mountPath: /dev/shm   
          
          resources:
            requests:
              cpu: "4"
              memory: "16Gi"
            limits:
              nvidia.com/gpu: 1
      volumes:
        - name: huggingface-cache
          persistentVolumeClaim:
            claimName: huggingface-cache
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi    