apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin-daemonset
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    matchLabels:
      name: nvidia-device-plugin-ds
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: nvidia-device-plugin-ds
    spec:
      # Only run on nodes labeled gpu=true
      nodeSelector:
        gpu: "true"

      #Tolerate both the built-in NVIDIA taint and the custom one
      tolerations:
        # existing toleration for the plugin itself
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule

        # new toleration so it can schedule onto gpu=true:NoSchedule
        - key: gpu
          operator: Equal
          value: "true"
          effect: NoSchedule

      containers:
      - image: nvcr.io/nvidia/k8s-device-plugin:v0.17.1
        name: nvidia-device-plugin-ctr
        env:
          - name: FAIL_ON_INIT_ERROR
            value: "false"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
          # mount the CDI specs from the host
          - name: cdi
            mountPath: /etc/cdi
            readOnly: true
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        # the host’s CDI directory
        - name: cdi
          hostPath:
            path: /etc/cdi
            type: DirectoryOrCreate