apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-mistral-7b-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 100Gi