apiVersion: v1
kind: Service
metadata:
  name: vllm-service
  namespace: vllm-ai
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: vllm
  sessionAffinity: None
  type: ClusterIP