apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-3b-vllm
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: llama-3b-vllm
  template:
    metadata:
      labels:
        app: llama-3b-vllm
    spec:
      hostIPC: true
      # Only schedule onto nodes labeled `gpu=true`
      nodeSelector:
        gpu: "true"
      tolerations:
        - key: "gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      volumes:
      - name: huggingface-cache
        persistentVolumeClaim:
          claimName: huggingface-cache
      # vLLM needs to access the host's shared memory for tensor parallel inference.
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: "8Gi"      

      containers:
        - name: llama-3b-vllm
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/bin/sh", "-c"]
          args: [
            "vllm serve unsloth/Llama-3.2-3B-Instruct --trust-remote-code --enable-chunked-prefill --max_num_batched_tokens 1024"
          ]
          ports:
            - containerPort: 8000
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vllm-hf-token
                  key: HUGGING_FACE_HUB_TOKEN
            - name: VLLM_LOGGING_LEVEL
              value: DEBUG

          volumeMounts:
            - name: huggingface-cache
              mountPath: /root/.cache/huggingface
            - name: dshm
              mountPath: /dev/shm   
          
          resources:
            limits:
              cpu: "10"
              memory: 20G
              nvidia.com/gpu: "1"
            requests:
              cpu: "2"
              memory: 6G
              nvidia.com/gpu: "1"

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 5    
        